<a href="https://colab.research.google.com/github/ucfilho/marquesgabi/blob/master/ANN_fotos_02_dez_19_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn.model_selection import train_test_split
import numpy as np
import cv2
import math
import pandas as pd
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score 
from mpl_toolkits.mplot3d import Axes3D, axes3d
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline

In [0]:
# funcao normatiza dados
def Normatiza(x):
    strings=list(x)
    for i in strings:
        max_x=x[i].max()
        min_x=x[i].min()
        a=(max_x+min_x)/2
        b=(max_x-min_x)/2
        x[i]=(x[i]-a)/b
    return x

In [0]:
# funcao retorna os dados a forma original
def Original(x,x_old):
    strings=list(x)
    for i in strings:
        max_x=x_old[i].max()
        min_x=x_old[i].min()
        a=(max_x+min_x)/2
        b=(max_x-min_x)/2
        x[i]=x[i]*b+a
    return x

In [4]:
!wget http://ftp.feq.ufu.br/ubirajara/Fotos_Treina_ANN_dez_2019.csv
Transfere='Fotos_Treina_ANN_dez_2019.csv'

--2019-12-19 15:23:27--  http://ftp.feq.ufu.br/ubirajara/Fotos_Treina_ANN_dez_2019.csv
Resolving ftp.feq.ufu.br (ftp.feq.ufu.br)... 200.19.144.11
Connecting to ftp.feq.ufu.br (ftp.feq.ufu.br)|200.19.144.11|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21508 (21K) [text/csv]
Saving to: ‘Fotos_Treina_ANN_dez_2019.csv.13’

Fotos_Treina_ANN_de 100%[===================>]  21.00K  36.7KB/s    in 0.6s    

2019-12-19 15:23:28 (36.7 KB/s) - ‘Fotos_Treina_ANN_dez_2019.csv.13’ saved [21508/21508]



In [0]:
df= pd.read_csv(Transfere) 

In [0]:
df['Type'] = df['Type'].map({'buraco':1, 'grao':2, 'indef':3}) 

In [0]:
X=df.iloc[:,2:12]
y=df.iloc[:,1]
y = pd.DataFrame(y, columns=['Type'])

In [0]:

# separa os dados em normatizados e originais
X_OLD=[]
X_OLD=X.copy()
X=Normatiza(X)
#print(X)

y_OLD=[]
y_OLD=y.copy()
y=Normatiza(y)
#print(y)


In [0]:
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [0]:
# define a rede neural 
N_Hidden=10
clf = MLPRegressor(solver='lbfgs',activation='tanh',alpha=1e-5,hidden_layer_sizes=(N_Hidden), 
                    random_state=1)

In [11]:
# treina a rede neural
clf.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:1321: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPRegressor(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=10, learning_rate='constant',
             learning_rate_init=0.001, max_iter=200, momentum=0.9,
             n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
             random_state=1, shuffle=True, solver='lbfgs', tol=0.0001,
             validation_fraction=0.1, verbose=False, warm_start=False)

In [0]:
# usa a rede neural treina em calculos para treino e teste
y_calc_train=clf.predict(X_train)
y_calc_test=clf.predict(X_test)


In [13]:
print(y_calc_test)



[ 0.60709854 -1.6330801  -0.40957103  0.5280218   1.4373316   0.7097988
 -1.25072818 -0.03272141 -1.31513826  0.11178674  0.3207174   1.07062779
  0.36490423 -0.81519259  0.50300299 -0.79310638  0.42002154 -0.90056747
  1.48419992 -0.51300576  0.67251767  0.78604294 -0.2038106   3.42867541]


In [0]:
# transforma a saida da rede em dataframe 
y_calc_train=pd.DataFrame(y_calc_train)
y_calc_test=pd.DataFrame(y_calc_test)
col_names=list(y_train)
y_calc_train.columns = col_names
y_calc_test.columns = col_names

In [15]:
# transforma dos dados calculados na forma original (nao normatizado)
y_calc_train=Original(y_calc_train,y_OLD)
y_calc_test=Original(y_calc_test,y_OLD)

y_train=Original(y_train,y_OLD)
y_test=Original(y_test,y_OLD)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [0]:
y_calc_train=np.array(y_calc_train)
for i in range(len(y_calc_train)):
  y_calc_train[i]=math.floor(y_calc_train[i])
  
y_calc_test=np.array(y_calc_test)
for i in range(len(y_calc_test)):
  y_calc_test[i]=math.floor(y_calc_test[i])

In [17]:
print(y_calc_test.ravel())
y_pred=pd.DataFrame(y_test)
y_calc_test=pd.DataFrame(y_calc_test)

[2. 0. 1. 2. 3. 2. 0. 1. 0. 2. 2. 3. 2. 1. 2. 1. 2. 1. 3. 1. 2. 2. 1. 5.]


In [18]:
# Evaluating the Algorithm
print(confusion_matrix(y_calc_test, y_pred))
print(classification_report(y_calc_test, y_pred))

[[0 2 0 1 0]
 [0 1 3 3 0]
 [0 2 4 4 0]
 [0 0 2 1 0]
 [0 0 1 0 0]]
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         3
         1.0       0.20      0.14      0.17         7
         2.0       0.40      0.40      0.40        10
         3.0       0.11      0.33      0.17         3
         5.0       0.00      0.00      0.00         1

    accuracy                           0.25        24
   macro avg       0.14      0.18      0.15        24
weighted avg       0.24      0.25      0.24        24



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
