<a href="https://colab.research.google.com/github/ucfilho/marquesgabi/blob/master/ANN_fotos_04_dez_19_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn.model_selection import train_test_split
import numpy as np
import cv2
import math
import pandas as pd
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score 
from mpl_toolkits.mplot3d import Axes3D, axes3d
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline

In [0]:
# funcao normatiza dados
def Normatiza(x):
    strings=list(x)
    for i in strings:
        max_x=x[i].max()
        min_x=x[i].min()
        a=(max_x+min_x)/2
        b=(max_x-min_x)/2
        x[i]=(x[i]-a)/b
    return x

In [0]:
# funcao retorna os dados a forma original
def Original(x,x_old):
    strings=list(x)
    for i in strings:
        max_x=x_old[i].max()
        min_x=x_old[i].min()
        a=(max_x+min_x)/2
        b=(max_x-min_x)/2
        x[i]=x[i]*b+a
    return x

In [4]:
!wget http://ftp.feq.ufu.br/ubirajara/Fotos_Treina_ANN_dez_2019.csv
Transfere='Fotos_Treina_ANN_dez_2019.csv'

--2019-12-19 21:17:14--  http://ftp.feq.ufu.br/ubirajara/Fotos_Treina_ANN_dez_2019.csv
Resolving ftp.feq.ufu.br (ftp.feq.ufu.br)... 200.19.144.11
Connecting to ftp.feq.ufu.br (ftp.feq.ufu.br)|200.19.144.11|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21508 (21K) [text/csv]
Saving to: ‘Fotos_Treina_ANN_dez_2019.csv.40’

Fotos_Treina_ANN_de 100%[===================>]  21.00K  50.4KB/s    in 0.4s    

2019-12-19 21:17:15 (50.4 KB/s) - ‘Fotos_Treina_ANN_dez_2019.csv.40’ saved [21508/21508]



In [0]:
df= pd.read_csv(Transfere) 

In [0]:
df['Type'] = df['Type'].map({'buraco':1, 'grao':2, 'indef':3}) 

In [0]:
X=df.iloc[:,2:12]
yw=df.iloc[:,1]


In [0]:
# reescreve a variavel de resposta em três saídas (zero e um) 
ref=np.array(yw)
row=len(ref)
y=np.zeros((row,3))
for i in range(row):
  if(ref[i]==1):
    y[i,0]=1
  else:
    if(ref[i]==2):
      y[i,1]=1
    else:
      y[i,2]=1


In [9]:

# separa os dados variaveis de entrada em normatizados e originais
X_OLD=[]
X_OLD=X.copy()
X=Normatiza(X)
#print(X)
y = pd.DataFrame(y, columns=['buraco', 'grao','indef'])


y_OLD=[]
y_OLD=y.copy()
y=Normatiza(y)
print(y)


     buraco  grao  indef
0       1.0  -1.0   -1.0
1       1.0  -1.0   -1.0
2       1.0  -1.0   -1.0
3       1.0  -1.0   -1.0
4       1.0  -1.0   -1.0
..      ...   ...    ...
115    -1.0  -1.0    1.0
116    -1.0  -1.0    1.0
117    -1.0  -1.0    1.0
118    -1.0  -1.0    1.0
119    -1.0  -1.0    1.0

[120 rows x 3 columns]


In [0]:
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [0]:
# define a rede neural 
N_Hidden=15
clf = MLPRegressor(solver='lbfgs',activation='tanh',alpha=1e-5,hidden_layer_sizes=(N_Hidden), 
                    random_state=0)


In [12]:
'''
N_Hidden=15
clf = MLPRegressor(solver='adam',activation='tanh',alpha=1e-5,
                   verbose=False,hidden_layer_sizes=(N_Hidden),
                   early_stopping=False,random_state=1)
'''

"\nN_Hidden=15\nclf = MLPRegressor(solver='adam',activation='tanh',alpha=1e-5,\n                   verbose=False,hidden_layer_sizes=(N_Hidden),\n                   early_stopping=False,random_state=1)\n"

In [0]:
#print(y_test)

In [14]:
# treina a rede neural
clf.fit(X_train, y_train)


MLPRegressor(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=15, learning_rate='constant',
             learning_rate_init=0.001, max_iter=200, momentum=0.9,
             n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
             random_state=0, shuffle=True, solver='lbfgs', tol=0.0001,
             validation_fraction=0.1, verbose=False, warm_start=False)

In [0]:
# usa a rede neural treina em calculos para treino e teste
y_calc_train=clf.predict(X_train)
y_calc_test=clf.predict(X_test)


In [0]:
row,col=y_test.shape
y_pred=np.zeros(row)

for i in range(row):
  if(y_calc_test[i,0]>0):
    y_pred[i]=1
  else:
    if(y_calc_test[i,1]>0):
      y_pred[i]=2
    else:
      y_pred[i]=3

row,col=y_test.shape
y_test=np.array(y_test)
y_inic=np.zeros(row)
for i in range(row):
  if(y_test[i,0]>0):
    y_inic[i]=1
  else:
    if(y_test[i,1]>0):
      y_inic[i]=2
    else:
      y_inic[i]=3

In [17]:
print(y_calc_test)

[[-0.64947553  0.79051901 -1.25271018]
 [ 0.54715922 -1.3346971  -0.09505566]
 [-1.44198862  0.99532731 -0.55067622]
 [-1.48027285 -0.46184443  1.02128353]
 [ 0.79902802 -1.28720083 -0.51492568]
 [-1.07855683 -1.55143599  1.57147635]
 [-0.77181146  1.30032985 -1.37037759]
 [-1.31236769 -0.24338554  0.66642495]
 [-0.34927389  0.08921495 -0.76191776]
 [ 0.16888699  0.55073246 -1.78406815]
 [-0.78992246  0.23419103 -0.48844561]
 [ 0.95071426 -1.36934477 -0.61691708]
 [-1.05067895 -0.467436    0.45179732]
 [-1.40057309  1.3367921  -1.0150949 ]
 [-0.21114183 -1.22339013  0.69145429]
 [ 0.30789358 -0.73947038 -0.60932598]
 [-0.74097837 -0.4047019   0.17838458]
 [-1.36127696  0.20027948  0.02660049]
 [ 0.19477172 -1.30077945  0.06526396]
 [ 2.3438527  -2.53681622 -0.84217554]
 [-0.79585934  0.92163069 -1.18983197]
 [-1.60843875 -0.57836672  1.23464715]
 [ 0.43183346 -0.80902894 -0.64281375]
 [ 0.27439868 -0.88224686 -0.41983599]]


In [0]:
# transforma a saida da rede em dataframe 
y_inic=pd.DataFrame(y_inic).astype(int)
y_pred=pd.DataFrame(y_pred).astype(int)
y_inic.columns = ['Type']
y_pred.columns = ['Type']

In [19]:
print(y_calc_test)

[[-0.64947553  0.79051901 -1.25271018]
 [ 0.54715922 -1.3346971  -0.09505566]
 [-1.44198862  0.99532731 -0.55067622]
 [-1.48027285 -0.46184443  1.02128353]
 [ 0.79902802 -1.28720083 -0.51492568]
 [-1.07855683 -1.55143599  1.57147635]
 [-0.77181146  1.30032985 -1.37037759]
 [-1.31236769 -0.24338554  0.66642495]
 [-0.34927389  0.08921495 -0.76191776]
 [ 0.16888699  0.55073246 -1.78406815]
 [-0.78992246  0.23419103 -0.48844561]
 [ 0.95071426 -1.36934477 -0.61691708]
 [-1.05067895 -0.467436    0.45179732]
 [-1.40057309  1.3367921  -1.0150949 ]
 [-0.21114183 -1.22339013  0.69145429]
 [ 0.30789358 -0.73947038 -0.60932598]
 [-0.74097837 -0.4047019   0.17838458]
 [-1.36127696  0.20027948  0.02660049]
 [ 0.19477172 -1.30077945  0.06526396]
 [ 2.3438527  -2.53681622 -0.84217554]
 [-0.79585934  0.92163069 -1.18983197]
 [-1.60843875 -0.57836672  1.23464715]
 [ 0.43183346 -0.80902894 -0.64281375]
 [ 0.27439868 -0.88224686 -0.41983599]]


In [20]:
# Evaluating the Algorithm
print(confusion_matrix(y_pred, y_inic))
print(classification_report(y_pred, y_inic))

[[1 2 6]
 [3 4 1]
 [1 3 3]]
              precision    recall  f1-score   support

           1       0.20      0.11      0.14         9
           2       0.44      0.50      0.47         8
           3       0.30      0.43      0.35         7

    accuracy                           0.33        24
   macro avg       0.31      0.35      0.32        24
weighted avg       0.31      0.33      0.31        24



In [21]:
print(y_pred)

    Type
0      2
1      1
2      2
3      3
4      1
5      3
6      2
7      3
8      2
9      1
10     2
11     1
12     3
13     2
14     3
15     1
16     3
17     2
18     1
19     1
20     2
21     3
22     1
23     1
