<a href="https://colab.research.google.com/github/ucfilho/marquesgabi/blob/master/ANN_fotos_03_dez_19_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn.model_selection import train_test_split
import numpy as np
import cv2
import math
import pandas as pd
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score 
from mpl_toolkits.mplot3d import Axes3D, axes3d
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline

In [0]:
# funcao normatiza dados
def Normatiza(x):
    strings=list(x)
    for i in strings:
        max_x=x[i].max()
        min_x=x[i].min()
        a=(max_x+min_x)/2
        b=(max_x-min_x)/2
        x[i]=(x[i]-a)/b
    return x

In [0]:
# funcao retorna os dados a forma original
def Original(x,x_old):
    strings=list(x)
    for i in strings:
        max_x=x_old[i].max()
        min_x=x_old[i].min()
        a=(max_x+min_x)/2
        b=(max_x-min_x)/2
        x[i]=x[i]*b+a
    return x

In [4]:
!wget http://ftp.feq.ufu.br/ubirajara/Fotos_Treina_ANN_dez_2019.csv
Transfere='Fotos_Treina_ANN_dez_2019.csv'

--2019-12-19 15:31:04--  http://ftp.feq.ufu.br/ubirajara/Fotos_Treina_ANN_dez_2019.csv
Resolving ftp.feq.ufu.br (ftp.feq.ufu.br)... 200.19.144.11
Connecting to ftp.feq.ufu.br (ftp.feq.ufu.br)|200.19.144.11|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21508 (21K) [text/csv]
Saving to: ‘Fotos_Treina_ANN_dez_2019.csv.14’

Fotos_Treina_ANN_de 100%[===================>]  21.00K  36.9KB/s    in 0.6s    

2019-12-19 15:31:05 (36.9 KB/s) - ‘Fotos_Treina_ANN_dez_2019.csv.14’ saved [21508/21508]



In [0]:
df= pd.read_csv(Transfere) 

In [0]:
df['Type'] = df['Type'].map({'buraco':1, 'grao':2, 'indef':3}) 

In [0]:
X=df.iloc[:,2:12]
y=df.iloc[:,1]
y = pd.DataFrame(y, columns=['Type'])

In [0]:

# separa os dados em normatizados e originais
X_OLD=[]
X_OLD=X.copy()
X=Normatiza(X)
#print(X)

y_OLD=[]
y_OLD=y.copy()
y=Normatiza(y)
#print(y)


In [0]:
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [0]:
# define a rede neural 
N_Hidden=10
clf = MLPRegressor(solver='lbfgs',activation='tanh',alpha=1e-5,hidden_layer_sizes=(N_Hidden), 
                    random_state=1)

In [11]:
# treina a rede neural
clf.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:1321: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPRegressor(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=10, learning_rate='constant',
             learning_rate_init=0.001, max_iter=200, momentum=0.9,
             n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
             random_state=1, shuffle=True, solver='lbfgs', tol=0.0001,
             validation_fraction=0.1, verbose=False, warm_start=False)

In [0]:
# usa a rede neural treina em calculos para treino e teste
y_calc_train=clf.predict(X_train)
y_calc_test=clf.predict(X_test)


In [13]:
print(y_calc_test)



[ 1.25544813e-01  1.38453138e+00 -9.32150627e-03  7.63886338e-01
 -2.03362701e+00  4.63235537e+00 -2.13069215e+00 -2.50582590e-01
  2.61737038e-01  5.10907014e-01 -1.67915294e+00 -5.18256109e+00
 -2.01991130e-01  1.58459682e+01  1.10836708e+00 -1.20762123e+00
  2.18157556e-01 -5.75918538e+00 -4.86914304e-01  1.30598558e+01
 -8.52233929e-02 -5.30969286e+00 -1.83894757e-01 -7.13948906e-01]


In [0]:
for i in range(len(y_calc_test)):
  if(y_calc_test[i]<(-1/3)):
    y_calc_test[i]=1
  else:
    if(y_calc_test[i]>(1/3)):
      y_calc_test[i]=3
    else:
      y_calc_test[i]=2

for i in range(len(y_calc_train)):
  if(y_calc_train[i]<(-1/3)):
    y_calc_train[i]=1
  else:
    if(y_calc_train[i]>(1/3)):
      y_calc_train[i]=3
    else:
      y_calc_train[i]=2

In [0]:
# transforma a saida da rede em dataframe 
y_calc_train=pd.DataFrame(y_calc_train)
y_calc_test=pd.DataFrame(y_calc_test)
col_names=list(y_train)
y_calc_train.columns = col_names
y_calc_test.columns = col_names

In [16]:
# transforma dos dados calculados na forma original (nao normatizado)
y_train=Original(y_train,y_OLD)
y_test=Original(y_test,y_OLD)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [17]:
'''
y_calc_train=np.array(y_calc_train)
for i in range(len(y_calc_train)):
  y_calc_train[i]=math.floor(y_calc_train[i])
  
y_calc_test=np.array(y_calc_test)
for i in range(len(y_calc_test)):
  y_calc_test[i]=math.floor(y_calc_test[i])
'''

'\ny_calc_train=np.array(y_calc_train)\nfor i in range(len(y_calc_train)):\n  y_calc_train[i]=math.floor(y_calc_train[i])\n  \ny_calc_test=np.array(y_calc_test)\nfor i in range(len(y_calc_test)):\n  y_calc_test[i]=math.floor(y_calc_test[i])\n'

In [18]:
# Evaluating the Algorithm
print(confusion_matrix(y_calc_test, y_test))
print(classification_report(y_calc_test, y_test))

[[3 4 2]
 [1 4 3]
 [2 1 4]]
              precision    recall  f1-score   support

         1.0       0.50      0.33      0.40         9
         2.0       0.44      0.50      0.47         8
         3.0       0.44      0.57      0.50         7

    accuracy                           0.46        24
   macro avg       0.46      0.47      0.46        24
weighted avg       0.47      0.46      0.45        24

