<a href="https://colab.research.google.com/github/ucfilho/marquesgabi/blob/master/Calculo_009_out_24_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# carrega as bibliotecas do python

In [0]:
%matplotlib inline
from matplotlib import pyplot as plt
import os 
import cv2
import zipfile
from skimage import data
from skimage import filters
from skimage import exposure
import numpy as np
import pandas as pd
from google.colab import files

In [3]:
!wget http://ftp.feq.ufu.br/ubirajara/Sugar_set_30_2019.zip
#!ls -l trash_nov_22_2018.zip


--2019-10-24 13:21:10--  http://ftp.feq.ufu.br/ubirajara/Sugar_set_30_2019.zip
Resolving ftp.feq.ufu.br (ftp.feq.ufu.br)... 200.19.144.11
Connecting to ftp.feq.ufu.br (ftp.feq.ufu.br)|200.19.144.11|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19584173 (19M) [application/zip]
Saving to: ‘Sugar_set_30_2019.zip.7’

Sugar_set_30_2019.z 100%[===================>]  18.68M  6.05MB/s    in 3.1s    

2019-10-24 13:21:13 (6.05 MB/s) - ‘Sugar_set_30_2019.zip.7’ saved [19584173/19584173]



In [0]:

file_name = zipfile.ZipFile('Sugar_set_30_2019.zip', 'r')
file_name.extractall() 

In [0]:
# all images are resized in variable x, are in gray in variable p and in variable w are dataframe
FILE='Sugar_set_30_2019.zip'
img_name=[]
x=[]
p=[]
w=[]


with zipfile.ZipFile(FILE, "r") as f:
    for name in f.namelist():
        img_name.append(name)
        #x.append(cv2.imread(name))
        x.append(cv2.resize(cv2.imread(name),(64,64)))

nrow=len(img_name)
ncol=64*64
pp=np.zeros((nrow,ncol))
for i in range(nrow):
    w.append(cv2.cvtColor(np.array(x[i]), cv2.COLOR_BGR2GRAY))
    pp[i,:]=w[i].ravel()

In [16]:
print(w)
#print(pp.shape)

[array([[104,  96, 108, ..., 117, 128, 118],
       [110, 104, 114, ..., 107, 115, 108],
       [117, 103, 118, ..., 114, 110, 125],
       ...,
       [121, 108, 118, ..., 113, 111, 115],
       [104, 122, 109, ..., 119, 117, 115],
       [102, 110, 110, ..., 123, 120, 120]], dtype=uint8), array([[130, 106, 123, ..., 113, 115, 103],
       [107, 112, 119, ..., 116, 114, 101],
       [113, 108, 110, ..., 108, 117,  98],
       ...,
       [114, 113, 120, ..., 126, 126, 115],
       [114, 114, 114, ..., 122, 119, 127],
       [117, 119, 111, ..., 115, 121, 127]], dtype=uint8), array([[118, 115, 116, ..., 116, 143, 104],
       [106, 120, 109, ..., 115, 109, 104],
       [121, 114, 109, ..., 124, 108, 117],
       ...,
       [110, 108, 107, ..., 117, 120, 114],
       [115, 119, 110, ..., 116, 111, 124],
       [110, 123, 109, ..., 113, 116, 114]], dtype=uint8), array([[116, 100, 101, ..., 118, 107, 114],
       [113, 105,  98, ..., 123, 119, 118],
       [112, 108, 111, ..., 134, 108, 

In [7]:
#variavel MP tem o somatorio de Pij
Num=len(img_name)
MP=[]
for k in range(Num):
  Soma=0
  for i in range(64):
    for j in range(64):
      Soma=Soma+p[k][i,j]
  MP.append(Soma)
print(MP)

[379131, 401229, 399430, 386293, 382921, 385930, 403846, 386138, 418977, 427227, 467134, 414421, 426800, 435215, 449231, 408467, 399262, 401986, 433264, 423563, 437965, 466633, 441547, 465707]


In [15]:
Num=len(img_name)
for k in range(Num):
  p=pp[k,:].reshape(64,64)
  print(p)
  print('===============')
  '''
  for i in range(64):
    for j in range(64):
      p[i,j]=p[i,j]/MP[k]
  '''

[[104.  96. 108. ... 117. 128. 118.]
 [110. 104. 114. ... 107. 115. 108.]
 [117. 103. 118. ... 114. 110. 125.]
 ...
 [121. 108. 118. ... 113. 111. 115.]
 [104. 122. 109. ... 119. 117. 115.]
 [102. 110. 110. ... 123. 120. 120.]]
[[130. 106. 123. ... 113. 115. 103.]
 [107. 112. 119. ... 116. 114. 101.]
 [113. 108. 110. ... 108. 117.  98.]
 ...
 [114. 113. 120. ... 126. 126. 115.]
 [114. 114. 114. ... 122. 119. 127.]
 [117. 119. 111. ... 115. 121. 127.]]
[[118. 115. 116. ... 116. 143. 104.]
 [106. 120. 109. ... 115. 109. 104.]
 [121. 114. 109. ... 124. 108. 117.]
 ...
 [110. 108. 107. ... 117. 120. 114.]
 [115. 119. 110. ... 116. 111. 124.]
 [110. 123. 109. ... 113. 116. 114.]]
[[116. 100. 101. ... 118. 107. 114.]
 [113. 105.  98. ... 123. 119. 118.]
 [112. 108. 111. ... 134. 108. 116.]
 ...
 [121. 115. 120. ... 114. 110. 109.]
 [110. 113. 112. ... 132. 118. 130.]
 [122. 108. 120. ... 116. 125. 118.]]
[[108.  94. 113. ... 114. 113. 116.]
 [ 97. 114. 105. ... 114. 114. 123.]
 [109. 116. 11

In [9]:
print(p[0][0,0])

0


In [10]:
95/379131

0.0002505730209347165

In [11]:
'''for k in range(Num):
  for i in range(64):
    for j in range(64):
      p[k][i,j]=p[k][i,j]/MP[k]'''

'for k in range(Num):\n  for i in range(64):\n    for j in range(64):\n      p[k][i,j]=p[k][i,j]/MP[k]'

In [12]:
print(p_new.shape)


NameError: ignored

In [0]:
'''
primeira foto:
[[0.00025057 0.00021365 0.00020573 ... 0.00020046 0.00017936 0.00019782]
 [0.00027431 0.00023475 0.00021892 ... 0.00021628 0.00020046 0.00021628]
 [0.0002664  0.00024002 0.00022683 ... 0.00023211 0.0002242  0.00023738]
 ...
 [0.00027431 0.00028222 0.00028222 ... 0.00025585 0.00025057 0.00026904]
 [0.00027167 0.00027695 0.00028222 ... 0.00026376 0.0002453  0.00024794]
 [0.0002664  0.00026904 0.00027959 ... 0.00027431 0.00024794 0.00024002]]'''

In [0]:
p=[]

In [0]:
WW=np.array([[1,2,3],[4,5,6],[7,8,9]])
WT=WW.ravel()
print(WT)
print(type(WT))
MM=WT.reshape(3,3)
print(MM)

In [0]:
Nrow=64
Ncol=64
Entropia=0 # estamos calculando da primeira foto
for i in range(Nrow):
  for j in range(Ncol):
    Entropia=Entropia-pw[0][i,j]*np.log(pw[0][i,j])
print("Entropia=",Entropia)


In [0]:
#print(Nfotos)

In [0]:
print(img_name)
Nfotos=len(img_name)
print(Nfotos)

In [0]:
Nfotos=len(img_name)
GLCM=np.zeros((Nfotos, 14))   # lembrar do ANN_Hydrofoil_Neuronio_set_17_2018.ipynb
Nrow=64
Ncol=64
print(GLCM.shape)
pw=p
for k in range(Nfotos):
  #p=np.copy(pw[k])
  print(pw[k])
  for i in range(Nrow):
    for j in range(Ncol):
      #print("i=%d j=%d k=%d"%(i,j,k))
      GLCM[k,7]=GLCM[k,7]-p[i,j]*np.log(p[i,j]) # entropia
      GLCM[k,0]=GLCM[k,0]+p[i,j]**2 #segundo momento angular
      GLCM[k,1]=GLCM[k,1]+(i-j)**2*p[i,j] #contraste
      GLCM[k,3]=GLCM[k,3]+(i-np.mean(p))**2*p[i,j] #Variancia



In [0]:
print(GLCM.shape)
print(pw[0].shape)

In [0]:
pd.set_option('display.max_columns', 30)
print(pd.DataFrame(GLCM))

In [0]:
GLCM=pd.DataFrame(GLCM)
pd.set_option('display.max_columns', 30)
print(GLCM.head(5))

In [0]:
print(np.mean(w[0]))

In [0]:
print(w)

In [0]:
pw=[]
for k in range(1):
  p_new=np.zeros((64,64))
  for i in range(64):
    for j in range(64):
      p_new[i,j]=p[k][i,j]/MP[k]
  pw.append(p_new)