<a href="https://colab.research.google.com/github/ucfilho/marquesgabi/blob/master/Calculo_010_out_24_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# carrega as bibliotecas do python

In [0]:
%matplotlib inline
from matplotlib import pyplot as plt
import os 
import cv2
import zipfile
from skimage import data
from skimage import filters
from skimage import exposure
import numpy as np
import pandas as pd
from google.colab import files

In [3]:
!wget http://ftp.feq.ufu.br/ubirajara/Sugar_set_30_2019.zip
#!ls -l trash_nov_22_2018.zip


--2019-10-24 13:55:46--  http://ftp.feq.ufu.br/ubirajara/Sugar_set_30_2019.zip
Resolving ftp.feq.ufu.br (ftp.feq.ufu.br)... 200.19.144.11
Connecting to ftp.feq.ufu.br (ftp.feq.ufu.br)|200.19.144.11|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19584173 (19M) [application/zip]
Saving to: ‘Sugar_set_30_2019.zip.4’

Sugar_set_30_2019.z 100%[===================>]  18.68M  3.95MB/s    in 4.7s    

2019-10-24 13:55:51 (3.95 MB/s) - ‘Sugar_set_30_2019.zip.4’ saved [19584173/19584173]



In [0]:

file_name = zipfile.ZipFile('Sugar_set_30_2019.zip', 'r')
file_name.extractall() 

In [0]:
# all images are resized in variable x, are in gray in variable p and in variable w are dataframe
FILE='Sugar_set_30_2019.zip'
img_name=[]
x=[]
p=[]
w=[]


with zipfile.ZipFile(FILE, "r") as f:
    for name in f.namelist():
        img_name.append(name)
        #x.append(cv2.imread(name))
        x.append(cv2.resize(cv2.imread(name),(64,64)))

nrow=len(img_name)
ncol=64*64
pp=np.zeros((nrow,ncol))
for i in range(nrow):
    w.append(cv2.cvtColor(np.array(x[i]), cv2.COLOR_BGR2GRAY))
    pp[i,:]=w[i].ravel()

In [6]:
print(sum(pp[0,:]))
# 379131

469057.0


In [7]:
print(pp.shape)
print(pp)

(24, 4096)
[[104.  96. 108. ... 123. 120. 120.]
 [130. 106. 123. ... 115. 121. 127.]
 [118. 115. 116. ... 113. 116. 114.]
 ...
 [125. 129. 125. ... 128. 134. 139.]
 [130. 123. 116. ... 137. 138. 137.]
 [134. 135. 131. ... 125. 136. 131.]]


In [8]:
soma=0
for i in range(64*64):
  soma=soma+pp[0,i]
print(soma)

469057.0


In [9]:
Num=len(img_name)
for k in range(Num):
  p=pp[k,:].reshape(64,64)
  print(p)
  print('===============')
  '''
  for i in range(64):
    for j in range(64):
      p[i,j]=p[i,j]/MP[k]
  '''

[[104.  96. 108. ... 117. 128. 118.]
 [110. 104. 114. ... 107. 115. 108.]
 [117. 103. 118. ... 114. 110. 125.]
 ...
 [121. 108. 118. ... 113. 111. 115.]
 [104. 122. 109. ... 119. 117. 115.]
 [102. 110. 110. ... 123. 120. 120.]]
[[130. 106. 123. ... 113. 115. 103.]
 [107. 112. 119. ... 116. 114. 101.]
 [113. 108. 110. ... 108. 117.  98.]
 ...
 [114. 113. 120. ... 126. 126. 115.]
 [114. 114. 114. ... 122. 119. 127.]
 [117. 119. 111. ... 115. 121. 127.]]
[[118. 115. 116. ... 116. 143. 104.]
 [106. 120. 109. ... 115. 109. 104.]
 [121. 114. 109. ... 124. 108. 117.]
 ...
 [110. 108. 107. ... 117. 120. 114.]
 [115. 119. 110. ... 116. 111. 124.]
 [110. 123. 109. ... 113. 116. 114.]]
[[116. 100. 101. ... 118. 107. 114.]
 [113. 105.  98. ... 123. 119. 118.]
 [112. 108. 111. ... 134. 108. 116.]
 ...
 [121. 115. 120. ... 114. 110. 109.]
 [110. 113. 112. ... 132. 118. 130.]
 [122. 108. 120. ... 116. 125. 118.]]
[[108.  94. 113. ... 114. 113. 116.]
 [ 97. 114. 105. ... 114. 114. 123.]
 [109. 116. 11

In [10]:
95/379131

0.0002505730209347165

In [11]:
'''
primeira foto:
[[0.00025057 0.00021365 0.00020573 ... 0.00020046 0.00017936 0.00019782]
 [0.00027431 0.00023475 0.00021892 ... 0.00021628 0.00020046 0.00021628]
 [0.0002664  0.00024002 0.00022683 ... 0.00023211 0.0002242  0.00023738]
 ...
 [0.00027431 0.00028222 0.00028222 ... 0.00025585 0.00025057 0.00026904]
 [0.00027167 0.00027695 0.00028222 ... 0.00026376 0.0002453  0.00024794]
 [0.0002664  0.00026904 0.00027959 ... 0.00027431 0.00024794 0.00024002]]'''

'\nprimeira foto:\n[[0.00025057 0.00021365 0.00020573 ... 0.00020046 0.00017936 0.00019782]\n [0.00027431 0.00023475 0.00021892 ... 0.00021628 0.00020046 0.00021628]\n [0.0002664  0.00024002 0.00022683 ... 0.00023211 0.0002242  0.00023738]\n ...\n [0.00027431 0.00028222 0.00028222 ... 0.00025585 0.00025057 0.00026904]\n [0.00027167 0.00027695 0.00028222 ... 0.00026376 0.0002453  0.00024794]\n [0.0002664  0.00026904 0.00027959 ... 0.00027431 0.00024794 0.00024002]]'

In [0]:
#print(Nfotos)

In [13]:
print(img_name)
Nfotos=len(img_name)
print(Nfotos)

['IMG_16_0634.jpg', 'IMG_16_0639.jpg', 'IMG_16_0640.jpg', 'IMG_18_0655.jpg', 'IMG_18_0656.jpg', 'IMG_18_0658.jpg', 'IMG_20_0680.jpg', 'IMG_20_0681.jpg', 'IMG_20_0688.jpg', 'IMG_25_0703.jpg', 'IMG_25_0706.jpg', 'IMG_25_0710.jpg', 'IMG_30_0732.jpg', 'IMG_30_0735.jpg', 'IMG_30_0737.jpg', 'IMG_35_0751.jpg', 'IMG_35_0757.jpg', 'IMG_35_0760.jpg', 'IMG_40_0776.jpg', 'IMG_40_0777.jpg', 'IMG_40_0780.jpg', 'IMG_70_0816.jpg', 'IMG_70_0818.jpg', 'IMG_70_0821.jpg']
24


In [14]:
Nfotos=len(img_name)
GLCM=np.zeros((Nfotos, 14))   # lembrar do ANN_Hydrofoil_Neuronio_set_17_2018.ipynb
Nrow=64
Ncol=64
print(GLCM.shape)

for k in range(Nfotos):
  Soma=np.sum(pp[k,:])
  p=pp[k,:].reshape(64,64)
  Soma=0
  for i in range(64):
    for j in range(64):
      Soma=Soma+p[i,j]
    print(Soma)
  for i in range(64):
    for j in range(64):
      p[i,j]=p[i,j]/Soma
  print(Soma)
  
  for i in range(Nrow):
    for j in range(Ncol):
      #print("i=%d j=%d k=%d"%(i,j,k))
      GLCM[k,7]=GLCM[k,7]-p[i,j]*np.log(p[i,j]) # entropia
      GLCM[k,0]=GLCM[k,0]+p[i,j]**2 #segundo momento angular
      GLCM[k,1]=GLCM[k,1]+(i-j)**2*p[i,j] #contraste
      GLCM[k,3]=GLCM[k,3]+(i-np.mean(p))**2*p[i,j] #Variancia



(24, 14)
6800.0
13873.0
20888.0
27948.0
34949.0
41843.0
48795.0
55699.0
62778.0
70709.0
78191.0
85214.0
92445.0
99600.0
106848.0
113969.0
121478.0
128680.0
135797.0
142964.0
150225.0
157551.0
165045.0
172617.0
180018.0
187290.0
194689.0
202028.0
209758.0
217106.0
224545.0
231942.0
239464.0
247389.0
255000.0
262441.0
269924.0
277370.0
284728.0
292175.0
299761.0
307183.0
314527.0
321879.0
329262.0
336626.0
343976.0
351357.0
358798.0
366283.0
373677.0
381097.0
388447.0
395776.0
403163.0
410450.0
417800.0
425066.0
432381.0
439749.0
447084.0
454459.0
461768.0
469057.0
469057.0
7080.0
14014.0
20921.0
27926.0
34996.0
42172.0
49312.0
56579.0
63790.0
70821.0
77943.0
85015.0
92168.0
99335.0
106348.0
113582.0
120797.0
128480.0
136097.0
143418.0
150871.0
158523.0
165983.0
173282.0
180600.0
188142.0
195702.0
203242.0
210947.0
218379.0
225947.0
233373.0
240716.0
248376.0
255977.0
263353.0
270835.0
278333.0
285767.0
293247.0
300842.0
308407.0
315759.0
323127.0
330524.0
337932.0
345295.0
352681.0
3601

In [15]:
print(GLCM.shape)

(24, 14)


In [16]:
pd.set_option('display.max_columns', 30)
print(pd.DataFrame(GLCM))

          0           1    2            3    4    5    6         7    8    9   \
0   0.000248  678.955816  0.0  1342.792871  0.0  0.0  0.0  8.311555  0.0  0.0   
1   0.000248  678.070012  0.0  1341.390053  0.0  0.0  0.0  8.311791  0.0  0.0   
2   0.000248  679.435567  0.0  1343.616627  0.0  0.0  0.0  8.311860  0.0  0.0   
3   0.000247  679.111101  0.0  1348.479196  0.0  0.0  0.0  8.311997  0.0  0.0   
4   0.000248  681.499431  0.0  1319.301898  0.0  0.0  0.0  8.311565  0.0  0.0   
5   0.000247  679.704257  0.0  1346.038479  0.0  0.0  0.0  8.312075  0.0  0.0   
6   0.000248  680.523164  0.0  1344.676385  0.0  0.0  0.0  8.311728  0.0  0.0   
7   0.000247  679.455304  0.0  1347.678192  0.0  0.0  0.0  8.312263  0.0  0.0   
8   0.000247  681.631983  0.0  1352.319159  0.0  0.0  0.0  8.312772  0.0  0.0   
9   0.000246  681.744642  0.0  1351.369373  0.0  0.0  0.0  8.314130  0.0  0.0   
10  0.000246  684.023601  0.0  1320.912469  0.0  0.0  0.0  8.314200  0.0  0.0   
11  0.000246  681.851713  0.

In [17]:
GLCM=pd.DataFrame(GLCM)
pd.set_option('display.max_columns', 30)
print(GLCM.head(5))

         0           1    2            3    4    5    6         7    8    9   \
0  0.000248  678.955816  0.0  1342.792871  0.0  0.0  0.0  8.311555  0.0  0.0   
1  0.000248  678.070012  0.0  1341.390053  0.0  0.0  0.0  8.311791  0.0  0.0   
2  0.000248  679.435567  0.0  1343.616627  0.0  0.0  0.0  8.311860  0.0  0.0   
3  0.000247  679.111101  0.0  1348.479196  0.0  0.0  0.0  8.311997  0.0  0.0   
4  0.000248  681.499431  0.0  1319.301898  0.0  0.0  0.0  8.311565  0.0  0.0   

    10   11   12   13  
0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  
