<a href="https://colab.research.google.com/github/ucfilho/marquesgabi/blob/master/Calculo_007_out_21_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# carrega as bibliotecas do python

In [0]:
%matplotlib inline
from matplotlib import pyplot as plt
import os 
import cv2
import zipfile
from skimage import data
from skimage import filters
from skimage import exposure
import numpy as np
import pandas as pd
from google.colab import files

In [3]:
!wget http://ftp.feq.ufu.br/ubirajara/Sugar_set_30_2019.zip
#!ls -l trash_nov_22_2018.zip


--2019-10-21 19:45:13--  http://ftp.feq.ufu.br/ubirajara/Sugar_set_30_2019.zip
Resolving ftp.feq.ufu.br (ftp.feq.ufu.br)... 200.19.144.11
Connecting to ftp.feq.ufu.br (ftp.feq.ufu.br)|200.19.144.11|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19584173 (19M) [application/zip]
Saving to: ‘Sugar_set_30_2019.zip’

Sugar_set_30_2019.z 100%[===================>]  18.68M  3.94MB/s    in 4.7s    

2019-10-21 19:45:20 (3.94 MB/s) - ‘Sugar_set_30_2019.zip’ saved [19584173/19584173]



In [0]:

file_name = zipfile.ZipFile('Sugar_set_30_2019.zip', 'r')
file_name.extractall() 

In [0]:
# all images are load in variable x...
FILE='Sugar_set_30_2019.zip'
img_name=[]
x=[]
p=[]
w=[]


with zipfile.ZipFile(FILE, "r") as f:
    for name in f.namelist():
        img_name.append(name)
        #x.append(cv2.imread(name))
        x.append(cv2.resize(cv2.imread(name),(64,64)))
        p.append(cv2.cvtColor(cv2.imread(name), cv2.COLOR_RGB2GRAY))

Num=len(img_name)

for i in range(Num):
    w.append(cv2.cvtColor(np.array(x[i]), cv2.COLOR_BGR2GRAY))


In [6]:
Num=len(img_name)
MP=[]
for k in range(Num):
  Soma=0
  for i in range(64):
    for j in range(64):
      Soma=Soma+p[k][i,j]
  MP.append(Soma)
print(MP)

[379131, 401229, 399430, 386293, 382921, 385930, 403846, 386138, 418977, 427227, 467134, 414421, 426800, 435215, 449231, 408467, 399262, 401986, 433264, 423563, 437965, 466633, 441547, 465707]


In [7]:
print(Num)

24


In [56]:
WW=np.array([[1,2,3],[4,5,6],[7,8,9]])
WT=WW.ravel()
print(WT)
print(type(WT))
MM=WT.reshape(3,3)
print(MM)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
95/379131

0.0002505730209347165

In [10]:
'''for k in range(Num):
  for i in range(64):
    for j in range(64):
      p[k][i,j]=p[k][i,j]/MP[k]'''

'for k in range(Num):\n  for i in range(64):\n    for j in range(64):\n      p[k][i,j]=p[k][i,j]/MP[k]'

In [0]:
pw=[]
for k in range(1):
  p_new=np.zeros((64,64))
  for i in range(64):
    for j in range(64):
      p_new[i,j]=p[k][i,j]/MP[k]
  pw.append(p_new)

In [44]:
print(p.shape)


(64, 64)


In [13]:
'''
primeira foto:
[[0.00025057 0.00021365 0.00020573 ... 0.00020046 0.00017936 0.00019782]
 [0.00027431 0.00023475 0.00021892 ... 0.00021628 0.00020046 0.00021628]
 [0.0002664  0.00024002 0.00022683 ... 0.00023211 0.0002242  0.00023738]
 ...
 [0.00027431 0.00028222 0.00028222 ... 0.00025585 0.00025057 0.00026904]
 [0.00027167 0.00027695 0.00028222 ... 0.00026376 0.0002453  0.00024794]
 [0.0002664  0.00026904 0.00027959 ... 0.00027431 0.00024794 0.00024002]]'''

'\nprimeira foto:\n[[0.00025057 0.00021365 0.00020573 ... 0.00020046 0.00017936 0.00019782]\n [0.00027431 0.00023475 0.00021892 ... 0.00021628 0.00020046 0.00021628]\n [0.0002664  0.00024002 0.00022683 ... 0.00023211 0.0002242  0.00023738]\n ...\n [0.00027431 0.00028222 0.00028222 ... 0.00025585 0.00025057 0.00026904]\n [0.00027167 0.00027695 0.00028222 ... 0.00026376 0.0002453  0.00024794]\n [0.0002664  0.00026904 0.00027959 ... 0.00027431 0.00024794 0.00024002]]'

In [0]:
p=[]

In [15]:
Nrow=64
Ncol=64
Entropia=0 # estamos calculando da primeira foto
for i in range(Nrow):
  for j in range(Ncol):
    Entropia=Entropia-pw[0][i,j]*np.log(pw[0][i,j])
print("Entropia=",Entropia)


Entropia= 8.312682777307495


In [18]:
print(Nfotos)

24


In [16]:
print(img_name)
Nfotos=len(img_name)
print(Nfotos)

['IMG_16_0634.jpg', 'IMG_16_0639.jpg', 'IMG_16_0640.jpg', 'IMG_18_0655.jpg', 'IMG_18_0656.jpg', 'IMG_18_0658.jpg', 'IMG_20_0680.jpg', 'IMG_20_0681.jpg', 'IMG_20_0688.jpg', 'IMG_25_0703.jpg', 'IMG_25_0706.jpg', 'IMG_25_0710.jpg', 'IMG_30_0732.jpg', 'IMG_30_0735.jpg', 'IMG_30_0737.jpg', 'IMG_35_0751.jpg', 'IMG_35_0757.jpg', 'IMG_35_0760.jpg', 'IMG_40_0776.jpg', 'IMG_40_0777.jpg', 'IMG_40_0780.jpg', 'IMG_70_0816.jpg', 'IMG_70_0818.jpg', 'IMG_70_0821.jpg']
24


In [37]:
Nfotos=len(img_name)
GLCM=np.zeros((Nfotos, 14))   # lembrar do ANN_Hydrofoil_Neuronio_set_17_2018.ipynb
Nrow=64
Ncol=64
print(GLCM.shape)
for k in range(Nfotos):
  p=np.copy(pw[k])
  print(pw[k])
  for i in range(Nrow):
    for j in range(Ncol):
      #print("i=%d j=%d k=%d"%(i,j,k))
      GLCM[k,7]=GLCM[k,7]-p[i,j]*np.log(p[i,j]) # entropia
      GLCM[k,0]=GLCM[k,0]+p[i,j]**2 #segundo momento angular
      GLCM[k,1]=GLCM[k,1]+(i-j)**2*p[i,j] #contraste
      GLCM[k,3]=GLCM[k,3]+(i-np.mean(p))**2*p[i,j] #Variancia



(24, 14)
[[0.00025057 0.00021365 0.00020573 ... 0.00020046 0.00017936 0.00019782]
 [0.00027431 0.00023475 0.00021892 ... 0.00021628 0.00020046 0.00021628]
 [0.0002664  0.00024002 0.00022683 ... 0.00023211 0.0002242  0.00023738]
 ...
 [0.00027431 0.00028222 0.00028222 ... 0.00025585 0.00025057 0.00026904]
 [0.00027167 0.00027695 0.00028222 ... 0.00026376 0.0002453  0.00024794]
 [0.0002664  0.00026904 0.00027959 ... 0.00027431 0.00024794 0.00024002]]


IndexError: ignored

In [32]:
print(GLCM.shape)
print(pw[0].shape)

(24, 14)
(64, 64)


In [26]:
pd.set_option('display.max_columns', 30)
print(pd.DataFrame(GLCM))

          0           1    2            3    4    5    6         7    8    9   \
0   0.000247  686.652368  0.0  1385.145331  0.0  0.0  0.0  8.312683  0.0  0.0   
1   0.000000    0.000000  0.0     0.000000  0.0  0.0  0.0  0.000000  0.0  0.0   
2   0.000000    0.000000  0.0     0.000000  0.0  0.0  0.0  0.000000  0.0  0.0   
3   0.000000    0.000000  0.0     0.000000  0.0  0.0  0.0  0.000000  0.0  0.0   
4   0.000000    0.000000  0.0     0.000000  0.0  0.0  0.0  0.000000  0.0  0.0   
5   0.000000    0.000000  0.0     0.000000  0.0  0.0  0.0  0.000000  0.0  0.0   
6   0.000000    0.000000  0.0     0.000000  0.0  0.0  0.0  0.000000  0.0  0.0   
7   0.000000    0.000000  0.0     0.000000  0.0  0.0  0.0  0.000000  0.0  0.0   
8   0.000000    0.000000  0.0     0.000000  0.0  0.0  0.0  0.000000  0.0  0.0   
9   0.000000    0.000000  0.0     0.000000  0.0  0.0  0.0  0.000000  0.0  0.0   
10  0.000000    0.000000  0.0     0.000000  0.0  0.0  0.0  0.000000  0.0  0.0   
11  0.000000    0.000000  0.

In [0]:
GLCM=pd.DataFrame(GLCM)
pd.set_option('display.max_columns', 30)
print(GLCM.head(5))

In [0]:
print(np.mean(w[0]))