<a href="https://colab.research.google.com/github/ucfilho/marquesgabi/blob/master/Calculo_011_out_24_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# carrega as bibliotecas do python

In [0]:
%matplotlib inline
from matplotlib import pyplot as plt
import os 
import cv2
import zipfile
from skimage import data
from skimage import filters
from skimage import exposure
import skimage.feature as sk
import numpy as np
import pandas as pd
from google.colab import files

In [3]:
!wget http://ftp.feq.ufu.br/ubirajara/Sugar_set_30_2019.zip
#!ls -l trash_nov_22_2018.zip


--2019-10-25 02:09:08--  http://ftp.feq.ufu.br/ubirajara/Sugar_set_30_2019.zip
Resolving ftp.feq.ufu.br (ftp.feq.ufu.br)... 200.19.144.11
Connecting to ftp.feq.ufu.br (ftp.feq.ufu.br)|200.19.144.11|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 19584173 (19M) [application/zip]
Saving to: ‘Sugar_set_30_2019.zip.8’

Sugar_set_30_2019.z 100%[===================>]  18.68M  4.94MB/s    in 3.8s    

2019-10-25 02:09:12 (4.94 MB/s) - ‘Sugar_set_30_2019.zip.8’ saved [19584173/19584173]



In [0]:

file_name = zipfile.ZipFile('Sugar_set_30_2019.zip', 'r')
file_name.extractall() 

In [0]:
# all images are resized in variable x, are in gray in variable p and in variable w are dataframe
FILE='Sugar_set_30_2019.zip'
img_name=[]
x=[]
p=[]
w=[]
Size=5 # trocar por 64 qdo acabar a analise

with zipfile.ZipFile(FILE, "r") as f:
    for name in f.namelist():
        img_name.append(name)
        #x.append(cv2.imread(name))
        x.append(cv2.resize(cv2.imread(name),(Size,Size)))

nrow=len(img_name)
ncol=Size*Size
pp=np.zeros((nrow,ncol))
for i in range(nrow):
    w.append(cv2.cvtColor(np.array(x[i]), cv2.COLOR_BGR2GRAY))
    pp[i,:]=w[i].ravel()

In [6]:
print(sum(pp[0,:]))
# 379131

2809.0


In [7]:
print(pp.shape)
print(pp)

(24, 25)
[[113. 102. 114. 119.  96. 115. 106.  99. 122. 122. 118. 108. 107. 111.
  117. 124. 113. 110. 116. 123. 109. 116. 108. 110. 111.]
 [104. 109. 112. 227. 123. 106. 111. 101. 107. 108. 113. 110. 113. 119.
  123. 128. 107. 109. 116. 126. 117. 118. 113. 123. 116.]
 [ 98. 101. 104. 107. 117. 120. 113.  88. 115. 108. 128. 126. 126. 104.
  119. 113. 127. 109. 107. 124. 112. 119. 114. 115. 115.]
 [117. 107. 104. 102. 116. 122. 124. 112. 112. 118. 101. 114. 116. 109.
  118. 105. 114. 112. 121. 110. 132. 118. 119. 124. 126.]
 [121. 106. 132. 123. 131. 107.  97. 113. 117. 111.  93. 118. 106. 110.
  112.  99. 121. 120. 105. 113.  97. 109. 107. 113. 102.]
 [104. 106.  97. 111. 134. 122. 107. 111. 117. 114. 105. 114. 128. 115.
  121. 112. 111. 107. 121. 132. 120. 110. 116. 118. 126.]
 [109. 116. 102. 117. 101. 120. 117. 112. 100. 124. 125. 113. 122. 120.
  119. 112. 107. 127. 120. 127. 115. 115. 110. 126. 120.]
 [ 94. 107. 110. 128.  99. 104. 109. 112. 120. 118. 122. 122. 116. 130.
  129. 10

In [8]:
soma=0
for i in range(Size*Size):
  soma=soma+pp[0,i]
print(soma)

2809.0


In [9]:
Num=len(img_name)
pd.set_option('display.max_columns', 64)
pd.set_option('display.max_rows', 64)
for k in range(Num):
  p=pp[k,:].reshape(Size,Size)
  if(k==0):
    print(pd.DataFrame(p))
  #print('===============')
  '''
  for i in range(64):
    for j in range(64):
      p[i,j]=p[i,j]/MP[k]
  '''

       0      1      2      3      4
0  113.0  102.0  114.0  119.0   96.0
1  115.0  106.0   99.0  122.0  122.0
2  118.0  108.0  107.0  111.0  117.0
3  124.0  113.0  110.0  116.0  123.0
4  109.0  116.0  108.0  110.0  111.0


In [10]:
95/379131

0.0002505730209347165

In [11]:
'''
primeira foto:
[[0.00025057 0.00021365 0.00020573 ... 0.00020046 0.00017936 0.00019782]
 [0.00027431 0.00023475 0.00021892 ... 0.00021628 0.00020046 0.00021628]
 [0.0002664  0.00024002 0.00022683 ... 0.00023211 0.0002242  0.00023738]
 ...
 [0.00027431 0.00028222 0.00028222 ... 0.00025585 0.00025057 0.00026904]
 [0.00027167 0.00027695 0.00028222 ... 0.00026376 0.0002453  0.00024794]
 [0.0002664  0.00026904 0.00027959 ... 0.00027431 0.00024794 0.00024002]]'''

'\nprimeira foto:\n[[0.00025057 0.00021365 0.00020573 ... 0.00020046 0.00017936 0.00019782]\n [0.00027431 0.00023475 0.00021892 ... 0.00021628 0.00020046 0.00021628]\n [0.0002664  0.00024002 0.00022683 ... 0.00023211 0.0002242  0.00023738]\n ...\n [0.00027431 0.00028222 0.00028222 ... 0.00025585 0.00025057 0.00026904]\n [0.00027167 0.00027695 0.00028222 ... 0.00026376 0.0002453  0.00024794]\n [0.0002664  0.00026904 0.00027959 ... 0.00027431 0.00024794 0.00024002]]'

In [12]:
'''
       0      1      2      3      4      5      6      7      8      9
0  104.0  102.0  115.0  117.0  115.0  117.0  116.0  113.0  107.0  128.0
1   99.0  120.0  110.0  248.0  112.0   98.0  107.0  187.0  109.0  104.0
2  119.0  115.0  112.0  118.0  112.0  112.0  102.0  110.0  127.0  120.0
3  119.0  116.0  120.0  115.0  113.0  123.0  119.0  103.0  112.0  113.0
4  110.0  114.0  131.0  115.0  109.0  109.0  114.0  132.0  115.0  122.0
5  114.0  116.0  123.0  113.0  118.0  106.0  115.0  186.0  110.0  127.0
6  109.0  105.0  111.0  109.0  109.0  200.0  113.0  107.0  116.0  125.0
7  113.0  114.0  111.0  112.0  125.0  119.0  124.0  126.0  117.0  118.0
8  118.0  110.0  105.0  108.0  108.0  111.0  108.0  121.0  122.0  114.0
9  114.0  111.0  112.0  110.0  111.0  115.0  115.0  119.0  112.0  116.0
'''

'\n       0      1      2      3      4      5      6      7      8      9\n0  104.0  102.0  115.0  117.0  115.0  117.0  116.0  113.0  107.0  128.0\n1   99.0  120.0  110.0  248.0  112.0   98.0  107.0  187.0  109.0  104.0\n2  119.0  115.0  112.0  118.0  112.0  112.0  102.0  110.0  127.0  120.0\n3  119.0  116.0  120.0  115.0  113.0  123.0  119.0  103.0  112.0  113.0\n4  110.0  114.0  131.0  115.0  109.0  109.0  114.0  132.0  115.0  122.0\n5  114.0  116.0  123.0  113.0  118.0  106.0  115.0  186.0  110.0  127.0\n6  109.0  105.0  111.0  109.0  109.0  200.0  113.0  107.0  116.0  125.0\n7  113.0  114.0  111.0  112.0  125.0  119.0  124.0  126.0  117.0  118.0\n8  118.0  110.0  105.0  108.0  108.0  111.0  108.0  121.0  122.0  114.0\n9  114.0  111.0  112.0  110.0  111.0  115.0  115.0  119.0  112.0  116.0\n'

In [13]:
print(w[0])
# print(sum(sum(w[0]))) fornece valor errado
# print(sum(w[0]))  fornece valor errado

[[113 102 114 119  96]
 [115 106  99 122 122]
 [118 108 107 111 117]
 [124 113 110 116 123]
 [109 116 108 110 111]]


In [24]:
A=113.0+102.0+114.0+119.0+96.0
B=115.0+106.0+99.0+122.0+122.0
C=118.0+108.0+107.0+111.0+117.0
D=124.0+113.0+110.0+116.0+123.0
E=109.0+116.0+108.0+110.0+111.0
print(A+B+C+D+E)

2809.0


In [15]:
print(img_name)
Nfotos=len(img_name)
print(Nfotos)

['IMG_16_0634.jpg', 'IMG_16_0639.jpg', 'IMG_16_0640.jpg', 'IMG_18_0655.jpg', 'IMG_18_0656.jpg', 'IMG_18_0658.jpg', 'IMG_20_0680.jpg', 'IMG_20_0681.jpg', 'IMG_20_0688.jpg', 'IMG_25_0703.jpg', 'IMG_25_0706.jpg', 'IMG_25_0710.jpg', 'IMG_30_0732.jpg', 'IMG_30_0735.jpg', 'IMG_30_0737.jpg', 'IMG_35_0751.jpg', 'IMG_35_0757.jpg', 'IMG_35_0760.jpg', 'IMG_40_0776.jpg', 'IMG_40_0777.jpg', 'IMG_40_0780.jpg', 'IMG_70_0816.jpg', 'IMG_70_0818.jpg', 'IMG_70_0821.jpg']
24


In [16]:
104/10599

0.00981224643834324

In [17]:
Nfotos=len(img_name)
GLCM=np.zeros((Nfotos, 14))   # lembrar do ANN_Hydrofoil_Neuronio_set_17_2018.ipynb
Nrow=Size
Ncol=Size
print(GLCM.shape)
#Soma=np.sum(pp[k,:])
for k in range(Nfotos):
  
  p=pp[k,:].reshape(Size,Size)
  Soma=0
  for i in range(Size):
    for j in range(Size):
      if(k==0): 
        print("i=",i,"j=",j,"pij=",p[i,j])
      Soma=Soma+p[i,j]
   
  if(k==0):
    print("=====",Soma,"=======") 
    print(p)
    print(pd.DataFrame(p));
  for i in range(Size):
    for j in range(Size):
      p[i,j]=p[i,j]/Soma

  
  if(k==0): 
    print('============================')
    print(Soma)
    #print(pd.DataFrame(p));
    print('============================');
  for i in range(Nrow):
    for j in range(Ncol):
      #print("i=%d j=%d k=%d"%(i,j,k))
      GLCM[k,7]=GLCM[k,7]-p[i,j]*np.log(p[i,j]) # entropia
      GLCM[k,0]=GLCM[k,0]+p[i,j]**2 #segundo momento angular
      GLCM[k,1]=GLCM[k,1]+(i-j)**2*p[i,j] #contraste
      GLCM[k,3]=GLCM[k,3]+(i-np.mean(p))**2*p[i,j] #Variancia



(24, 14)
i= 0 j= 0 pij= 113.0
i= 0 j= 1 pij= 102.0
i= 0 j= 2 pij= 114.0
i= 0 j= 3 pij= 119.0
i= 0 j= 4 pij= 96.0
i= 1 j= 0 pij= 115.0
i= 1 j= 1 pij= 106.0
i= 1 j= 2 pij= 99.0
i= 1 j= 3 pij= 122.0
i= 1 j= 4 pij= 122.0
i= 2 j= 0 pij= 118.0
i= 2 j= 1 pij= 108.0
i= 2 j= 2 pij= 107.0
i= 2 j= 3 pij= 111.0
i= 2 j= 4 pij= 117.0
i= 3 j= 0 pij= 124.0
i= 3 j= 1 pij= 113.0
i= 3 j= 2 pij= 110.0
i= 3 j= 3 pij= 116.0
i= 3 j= 4 pij= 123.0
i= 4 j= 0 pij= 109.0
i= 4 j= 1 pij= 116.0
i= 4 j= 2 pij= 108.0
i= 4 j= 3 pij= 110.0
i= 4 j= 4 pij= 111.0
===== 2809.0 =======
[[113. 102. 114. 119.  96.]
 [115. 106.  99. 122. 122.]
 [118. 108. 107. 111. 117.]
 [124. 113. 110. 116. 123.]
 [109. 116. 108. 110. 111.]]
       0      1      2      3      4
0  113.0  102.0  114.0  119.0   96.0
1  115.0  106.0   99.0  122.0  122.0
2  118.0  108.0  107.0  111.0  117.0
3  124.0  113.0  110.0  116.0  123.0
4  109.0  116.0  108.0  110.0  111.0
2809.0


In [18]:
nrow,ncol=w[0].shape;print(nrow);print(ncol)

5
5


In [19]:
print(GLCM.shape)

(24, 14)


In [20]:
print(p)

[[0.0445151  0.04324324 0.04006359 0.03720191 0.03974563]
 [0.04133545 0.04038156 0.03974563 0.04133545 0.04197138]
 [0.03751987 0.03497615 0.0381558  0.03974563 0.04165342]
 [0.04038156 0.03879173 0.04038156 0.03688394 0.0445151 ]
 [0.03942766 0.03847377 0.04356121 0.03720191 0.03879173]]


In [21]:
pd.set_option('display.max_columns', 30)
print(pd.DataFrame(GLCM))

           0         1    2         3    4    5    6         7    8    9   10  \
0   0.040159  4.006764  0.0  5.873156  0.0  0.0  0.0  3.216867  0.0  0.0  0.0   
1   0.041540  4.282528  0.0  5.762803  0.0  0.0  0.0  3.203164  0.0  0.0  0.0   
2   0.040287  4.030399  0.0  5.979967  0.0  0.0  0.0  3.215219  0.0  0.0  0.0   
3   0.040175  4.015663  0.0  6.027608  0.0  0.0  0.0  3.216685  0.0  0.0  0.0   
4   0.040313  4.043838  0.0  5.656749  0.0  0.0  0.0  3.214975  0.0  0.0  0.0   
5   0.040234  4.056964  0.0  5.948915  0.0  0.0  0.0  3.215969  0.0  0.0  0.0   
6   0.040177  3.895373  0.0  5.944445  0.0  0.0  0.0  3.216637  0.0  0.0  0.0   
7   0.040276  3.931919  0.0  6.036687  0.0  0.0  0.0  3.215371  0.0  0.0  0.0   
8   0.040229  3.993338  0.0  6.066993  0.0  0.0  0.0  3.216015  0.0  0.0  0.0   
9   0.040272  3.979461  0.0  5.888981  0.0  0.0  0.0  3.215601  0.0  0.0  0.0   
10  0.040134  3.934069  0.0  5.729726  0.0  0.0  0.0  3.217205  0.0  0.0  0.0   
11  0.041463  3.928237  0.0 

In [22]:
GLCM=pd.DataFrame(GLCM)
pd.set_option('display.max_columns', 30)
print(GLCM.head(5))

          0         1    2         3    4    5    6         7    8    9   10  \
0  0.040159  4.006764  0.0  5.873156  0.0  0.0  0.0  3.216867  0.0  0.0  0.0   
1  0.041540  4.282528  0.0  5.762803  0.0  0.0  0.0  3.203164  0.0  0.0  0.0   
2  0.040287  4.030399  0.0  5.979967  0.0  0.0  0.0  3.215219  0.0  0.0  0.0   
3  0.040175  4.015663  0.0  6.027608  0.0  0.0  0.0  3.216685  0.0  0.0  0.0   
4  0.040313  4.043838  0.0  5.656749  0.0  0.0  0.0  3.214975  0.0  0.0  0.0   

    11   12   13  
0  0.0  0.0  0.0  
1  0.0  0.0  0.0  
2  0.0  0.0  0.0  
3  0.0  0.0  0.0  
4  0.0  0.0  0.0  


In [23]:
#print(Nfotos)

##Then I say 


glcm = sk.greycomatrix(x[0], [1],[0])
print(glcm[0])

ValueError: ignored