<a href="https://colab.research.google.com/github/ucfilho/marquesgabi/blob/master/SVM_fotos_02_dez_17_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn.model_selection import train_test_split
import numpy as np
import cv2
import pandas as pd
from sklearn.svm import SVC
import random
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline

In [0]:
!wget http://ftp.feq.ufu.br/ubirajara/Fotos_Treina_ANN_dez_2019.csv
Transfere='Fotos_Treina_ANN_dez_2019.csv'

--2019-12-17 23:14:41--  http://ftp.feq.ufu.br/ubirajara/Fotos_Treina_ANN_dez_2019.csv
Resolving ftp.feq.ufu.br (ftp.feq.ufu.br)... 200.19.144.11
Connecting to ftp.feq.ufu.br (ftp.feq.ufu.br)|200.19.144.11|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21508 (21K) [text/csv]
Saving to: ‘Fotos_Treina_ANN_dez_2019.csv.6’

Fotos_Treina_ANN_de 100%[===================>]  21.00K  30.6KB/s    in 0.7s    

2019-12-17 23:14:42 (30.6 KB/s) - ‘Fotos_Treina_ANN_dez_2019.csv.6’ saved [21508/21508]



In [0]:
df= pd.read_csv(Transfere) 

In [0]:
df['Type'] = df['Type'].map({'buraco':1, 'grao':2, 'indef':3}) 

In [0]:
X=df.iloc[:,2:12]
y=df.iloc[:,1]

In [0]:
# Train Test Split
random.seed(13)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [0]:
print(y_test)

107    3
118    3
58     2
6      1
76     2
114    3
51     2
8      1
39     1
57     2
99     3
81     3
12     1
97     3
48     2
37     1
27     1
113    3
108    3
72     2
2      1
102    3
60     2
59     2
88     3
103    3
115    3
100    3
98     3
50     2
86     3
67     2
109    3
71     2
84     3
10     1
Name: Type, dtype: int64


In [0]:
# Feature Scaling
#svclassifier = SVC(kernel='linear')
#svclassifier = SVC(kernel='rbf')
# svclassifier = SVC(kernel='poly', C=0.025) #demorou muito 
#svclassifier =SVC(kernel='linear', C=1E10)
#C = 1e6 
#clf = SVC(kernel='rbf', C=C)
#clf = SVC(kernel='poly', C=C)
#clf = SVC(C=0.0001, kernel='poly', degree=2, gamma=2)
clf =  SVC(kernel = 'rbf', C = 100, gamma = 0.1)
clf.fit(X_train, y_train)

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred = clf.predict(X_test)

In [0]:
# Evaluating the Algorithm
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 8  0  0]
 [11  0  0]
 [17  0  0]]
              precision    recall  f1-score   support

           1       0.22      1.00      0.36         8
           2       0.00      0.00      0.00        11
           3       0.00      0.00      0.00        17

    accuracy                           0.22        36
   macro avg       0.07      0.33      0.12        36
weighted avg       0.05      0.22      0.08        36



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
